# https://ci.appveyor.com/project/jnsebgosselin/appconfigs

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master

skip_commits:
  files:
    - docs/*
    - '**/*.html'
    - '**/*.md'
    - '**/*.png'
    - '**/*.svg'
    - '**/*.jpg'

environment:
  global:
    APPCONFIGS_VERSION: "v0.1.0.dev0"

  matrix:
    - PYTHON: "C:\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

platform:
  -x64

skip_branch_with_pr: true

install:
  # Cancel older builds for the same PR.
  # Credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  
  # Setup SYS PATH.
  - set "PATH=%PYTHON%;%PYTHON%/Scripts;%PYTHON%/Library/bin;%PATH%"
  
  # Setup Conda.
  - python -m pip install -r requirements.txt
  - python -m pip install -r requirements-dev.txt

build: false

test_script:
  - python runtests.py
  
after_test:
  - IF ["%APPVEYOR_PULL_REQUEST_NUMBER%"]==[""] (%PYTHON%/python.exe setup.py sdist bdist_wheel)

artifacts:
  - path: 'dist/*.whl'
  - path: 'dist/*.tar.gz'

on_success:
  - codecov

on_finish:
  - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
